return {
  -- {
  --   "folke/noice.nvim",
  --   enabled = false,
  -- },
  -- {
  --   "rcarriga/nvim-notify",
  --   enabled = false,
  -- },
  -- {
  --   "nvimdev/dashboard-nvim",
  --   enabled = false,
  -- },
  -- {
  --   "echasnovski/mini.pairs",
  --   enabled = false,
  -- },
  -- {
  --   "echasnovski/mini.ai",
  --   enabled = false,
  -- },
  -- {
  --   "lukas-reineke/indent-blankline.nvim",
  --   enabled = false,
  -- },
}
