colors.draw_bold_text_with_bright_colors = true
# background_opacity = 0.99
# "window.dynamic_title" = true
live_config_reload = true

[window.padding]
x = 6
y = 6

[scrolling]
history = 100000
multiplier = 3

[font]
size = 14
# use_thin_strokes = true

[font.normal]
family = "FiraCode Nerd Font"
style = "Regular"

[font.bold]
family = "FiraCode Nerd Font"
style = "SemiBold"

[font.italic]
family = "FiraCode Nerd Font"
style = "Italic"

[font.bold_italic]
family = "FiraCode Nerd Font"
style = "SemiBold Italic"


[colors.primary]
background = "#1a1b26"
foreground = "#a9b1d6"

[colors.normal]
black = "#32344a"
red = "#f7768e"
green = "#9ece6a"
yellow = "#e0af68"
blue = "#7aa2f7"
magenta = "#ad8ee6"
cyan = "#449dab"
white = "#787c99"

[colors.bright]
black = "#444b6a"
red = "#ff7a93"
green = "#b9f27c"
yellow = "#ff9e64"
blue = "#7da6ff"
magenta = "#bb9af7"
cyan = "#0db9d7"
white = "#acb0d0"

[bell]
animation = "EaseOutExpo"
duration = 300
color = "0xffffff"

[selection]
semantic_escape_chars = ",│`|:\"' ()[]{}<>\t"
save_to_clipboard = true

[cursor]
style = "Block"
unfocused_hollow = true

[shell]
program = "/usr/local/bin/fish"
args = [ "--login" ]
