general.live_config_reload = true


# font
font.normal.family = "ComicShannsMono Nerd Font"
font.size = 14
font.offset.x = 0
font.offset.y = 12

#window
window.opacity = 0.5
window.padding.x = 12
window.padding.y = 12
window.blur = true
window.dynamic_title = false
window.decorations = "Full"

cursor.style = "Block"

mouse.hide_when_typing = true
